using System.Linq;
using System.Text;
using Content.Client._Common.Consent;
using Content.Client._Floof.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Coyote.SniffAndSmell;
using Content.Shared._Floof.CCVar;
using Linguini.Shared.Types;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using ScentData = Content.Shared._Coyote.SniffAndSmell.Scent;

namespace Content.Client._Floof.Scent;

/// <remarks>
///     This is shitcode I threw together in 3 hours. Don't expect it to be pretty.
///     I'm using IPrototype everywhere instead of concrete ScentPrototype because that's what PrototypeDropdown is using,
///     and I'm too lazy to change it.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class ScentsEditorDialog : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IClientConsentManager _consent = default!;

    public PrototypeDropdownWithSearch AddScentDropdown;

    public List<ScentData> CurrentData = new();
    public List<ScentPreset> Presets = new();
    public bool HasLewdConsent = true;

    public event Action<List<ScentData>>? OnSave;

    public ScentsEditorDialog(IDependencyCollection deps)
    {
        deps.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AddScentDropdown = new(
            GetPrototypeName,
            FilterPrototypes,
            typeof(ScentPrototype),
            deps);
        AddScentDropdown.Title = Loc.GetString("scent-editor-dropdown-title");
        AddScentDropdown.OnPrototypeChosen += AddScent;
        PrimaryContainer.AddChild(AddScentDropdown);

        SavePresetButton.OnPressed += _ => SaveCurrentAsPreset();

        SaveButton.OnPressed += _ =>
        {
            Save();
            Close();
        };
        CancelButton.OnPressed += _ => Close();
    }

    public string GetPrototypeName(IPrototype scentPrototype)
    {
        if (scentPrototype is not ScentPrototype s)
            return string.Empty;

        var sb = new StringBuilder(30);
        if (s.Lewd)
            sb.Append(Loc.GetString("scent-editor-prefix-lewd"));
        if (s.Stinky)
            sb.Append(Loc.GetString("scent-editor-prefix-stinky"));

        sb.Append(Loc.GetString(s.ScentsExamine.FirstOrDefault(defaultValue: s.ID))); // I don't have anything better
        return sb.ToString();
    }

    private bool FilterPrototypes(IPrototype scentPrototype)
    {
        if (scentPrototype is not ScentPrototype s || s.Abstract)
            return true;

        return !s.Lewd || HasLewdConsent;
    }

    /// <summary>
    ///     Load scent data from a component.
    /// </summary>
    public void LoadFrom(ScentComponent comp)
    {
        CurrentData.Clear();
        CurrentData.AddRange(comp.Scents);
        UpdateScentsContainer();
    }

    public void Save()
    {
        OnSave?.Invoke(CurrentData);
        SavePresets(); // Presets are saved when adding a new preset, but NOT saved when deleting one. So pressing save confirms deletions.

        UpdateScentsContainer();
        UpdatePresetsContainer();
    }

    protected override void Opened()
    {
        HasLewdConsent = !_consent.HasConsent("CantSmellLewdScents"); // Note: inverse.

        var presetsStr = _cfg.GetCVar(FloofCCVars.ScentPresets);
        try
        {
            var presets = ScentPreset.DeserializeMany(presetsStr);
            Presets.Clear();
            Presets.AddRange(presets);
            UpdatePresetsContainer();
        }
        catch (Exception e)
        {
            Log.Error($"Failed to parse scent presets: {e}");
        }
    }

    private void UpdateScentsContainer()
    {
        CurrentScentsContainer.RemoveAllChildren();
        foreach (var scent in CurrentData.ToArray())
        {
            if (!_protoMan.TryIndex(scent.ScentProto, out var proto))
            {
                CurrentData.Remove(scent);
                continue;
            }

            var item = new SimpleRemovableItem { Title = GetPrototypeName(proto) };
            item.OnDelete += () =>
            {
                CurrentData.Remove(scent);
                UpdateScentsContainer(); // Shouldn't ever be recursive? I think not.
            };
            CurrentScentsContainer.AddChild(item);
        }
    }

    private void UpdatePresetsContainer()
    {
        PresetsContainer.RemoveAllChildren();
        foreach (var preset in Presets.ToArray())
        {
            var item = new SimpleRemovableItem { Title = preset.Name };
            item.AddStyleClass("OpenRight");
            item.AddStyleClass(ContainerButton.StyleClassButton);

            item.OnPressed += _ =>
            {
                LoadPreset(preset);
            };
            item.OnDelete += () =>
            {
                Presets.Remove(preset);
                UpdatePresetsContainer();
            };
            PresetsContainer.AddChild(item);
        }
    }

    private void LoadPreset(ScentPreset preset)
    {
        CurrentData.Clear();
        CurrentData.AddRange(preset.scents);
        UpdateScentsContainer();
    }

    /// <summary>
    ///     Adds a scent and refreshes the ui.
    /// </summary>
    public void AddScent(IPrototype scent)
    {
        if (scent is not ScentPrototype)
            return;

        CurrentData.Add(new ScentData(scent.ID, Guid.NewGuid().ToString()));
        UpdateScentsContainer();
    }

    /// <summary>
    ///     Adds a preset and refreshes the UI.
    /// </summary>
    public void AddPreset(ScentPreset preset, bool forceSave)
    {
        // Remove all presets that share the same name
        Presets.RemoveAll(it => it.Name.Equals(preset.Name, StringComparison.InvariantCultureIgnoreCase));

        Presets.Add(preset);
        UpdatePresetsContainer();

        if (forceSave)
            SavePresets();
    }

    private void SaveCurrentAsPreset()
    {
        var name = PresetNameEdit.Text.Trim();

        // Warn the user with a field hint
        if (name.Length < 3 || name.Length > 30)
        {
            PresetNameEdit.PlaceHolder = Loc.GetString("scent-editor-hint-invalid-name");
            return;
        }

        PresetNameEdit.PlaceHolder = null;

        var values = CurrentData.ToList();
        var preset = new ScentPreset(name, values);

        AddPreset(preset, true);
    }

    private void SavePresets()
    {
        try
        {
            var serialized = ScentPreset.SerializeMany(Presets);
            _cfg.SetCVar(FloofCCVars.ScentPresets, serialized);
            _cfg.SaveToFile();
        }
        catch (Exception e)
        {
            Log.Error($"Failed to save scent presets: {e}");
        }
    }

    public sealed class ScentPreset
    {
        public string Name;
        public List<ScentData> scents;

        public const char
            PresetSeparator = ';', // Separator for presets in a cvar
            ScentSeparator = ','; // Separator for scents in a preset

        public ScentPreset(string name, List<ScentData> scents)
        {
            this.scents = scents;
            Name = name;
        }

        public void Deserialize(string value)
        {
            // First value is the name
            var values = value.Split(ScentSeparator);
            if (values.Length == 0)
            {
                Name = "<error>";
                return;
            }

            Name = values[0];

            foreach (var s in values.AsSpan(1))
            {
                if (s.Length > 0 && s.Length < 30) // Arbitrary limit
                    scents.Add(new ScentData(s, Guid.NewGuid().ToString())); // Todo: whyy does this shit use cryptographic random
            }
        }

        public string Serialize()
        {
            var sanitized = scents.Select(it =>
                it.ScentProto.ToString().Replace(PresetSeparator, '?').Replace(ScentSeparator, ' '));

            return Name + ScentSeparator + string.Join(ScentSeparator, sanitized); // First value is always the name
        }

        // Many-serialized strings are stored in cvars
        public static List<ScentPreset> DeserializeMany(string value)
        {
            var result = new List<ScentPreset>();
            foreach (var presetString in value.Split(PresetSeparator))
            {
                var preset = new ScentPreset(string.Empty, new());
                preset.Deserialize(presetString);
                result.Add(preset);
            }

            return result;
        }

        public static string SerializeMany(List<ScentPreset> presets)
        {
            return string.Join(PresetSeparator, presets.Select(it => it.Serialize()));
        }
    }
}
