using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Scent;


/// <summary>
///     Simple list item that exposes a title text field and a delete action.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SimpleRemovableItem : ContainerButton
{
    public string Title
    {
        get => NameLabel.Text ?? string.Empty;
        set => NameLabel.Text = value;
    }

    public event Action? OnDelete;

    public SimpleRemovableItem()
    {
        RobustXamlLoader.Load(this);
        DeleteButton.OnPressed += _ => OnDelete?.Invoke();
    }
}
