using System.Linq;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Floof.UI;

/// <summary>
///     Shows a dropdown with a search bar that allows the user to select one of the prototypes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeDropdownWithSearch : BoxContainer
{
    public string Title
    {
        get => ToggleButton.Text ?? string.Empty;
        set => ToggleButton.Text = value;
    }

    /// <summary>
    ///     Selects dropdown menu text for a prototype.
    /// </summary>
    public Func<IPrototype, string> TextSelector;

    /// <summary>
    ///     Selects which prototypes to show.
    /// </summary>
    public Func<IPrototype, bool>? PrototypeFilter;

    /// <summary>
    ///     Prototypes to show, expressed as the prototype kind.
    /// </summary>
    public string PrototypeKind;

    /// <summary>
    ///     Action fired when a prototype is chosen.
    /// </summary>
    public event Action<IPrototype>? OnPrototypeChosen;

    private PrototypeDropdownPopup? _currentPopup;

    private IDependencyCollection _deps;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly IUserInterfaceManager _userMan = default!;

    public PrototypeDropdownWithSearch(Func<IPrototype, string> textSelector, Func<IPrototype, bool>? prototypeFilter, Type prototypeKind, IDependencyCollection deps)
    {
        RobustXamlLoader.Load(this);

        TextSelector = textSelector;
        PrototypeFilter = prototypeFilter;

        _deps = deps;
        _deps.InjectDependencies(this);
        if (!_protoMan.TryGetKindFrom(prototypeKind, out var kind))
            Log.Error($"Prototype kind {PrototypeKind} does not exist!");

        PrototypeKind = kind ?? "<Unknown prototype kind>";

        ToggleButton.OnToggled += args => ToggleMenu(args.Pressed);
    }

    [Obsolete("Static IoC is obsolete, this is just here for xaml")]
    public PrototypeDropdownWithSearch() : this(p => "override this!", null, typeof(EntityPrototype), IoCManager.Instance!) {}

    private void ToggleMenu(bool show)
    {
        if (show)
        {
            // No point in keeping it in memory when it's not needed
            _currentPopup?.Orphan();
            _currentPopup = _userMan.CreatePopup<PrototypeDropdownPopup>();
            _currentPopup.OnPopupHide += () => ToggleButton.Pressed = false;

            var globalPos = GlobalPosition;
            var (minX, minY) = _currentPopup.MinSize;
            var box = UIBox2.FromDimensions(
                globalPos,
                new(Math.Max(minX, Width), minY));

            var entries = GetEntries().ToList();
            var texts = entries.Select(TextSelector);

            _currentPopup.Open(box);
            _currentPopup.SetEntries(texts);
            _currentPopup.OnOptionChosen += i => ChooseOption(entries[i]);
        }
        else
        {
            _currentPopup?.Orphan();
            _currentPopup = null;
        }
    }

    public void ChooseOption(IPrototype entry)
    {
        ToggleMenu(false);
        OnPrototypeChosen?.Invoke(entry);
    }

    private IEnumerable<IPrototype> GetEntries()
    {
        var protos = _protoMan.EnumeratePrototypes(PrototypeKind);
        if (PrototypeFilter is not null)
            protos = protos.Where(PrototypeFilter);
        return protos.OrderBy(it => it.ID);
    }
}
