using System.Linq;
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared._DV.CCVars;
using Content.Shared.CCVar;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Floof.UI;

[GenerateTypedNameReferences]
internal sealed partial class PrototypeDropdownPopup : Popup
{
    public event Action<int>? OnOptionChosen;
    private List<string>? Options;

    public PrototypeDropdownPopup()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += args => UpdateFilters(args.Text);
    }

    public void SetEntries(IEnumerable<string> entries)
    {
        Options = entries.ToList();
        SearchBar.Text = string.Empty;

        EntryContainer.RemoveAllChildren();
        for (int i = 0; i < Options.Count; i++)
        {
            var entry = Options[i];
            var control = new Button()
            {
                StyleClasses = { "OpenBoth" },
                Text = entry,
                HorizontalExpand = true
            };

            var iCaptured = i; // To avoid capturing the loop variable
            control.OnPressed += _ => Choose(iCaptured);
            EntryContainer.AddChild(control);
        }
    }

    public void UpdateFilters(string query)
    {
        query = query.Trim();
        foreach (var entry in EntryContainer.Children)
        {
            if (entry is not Button b)
                continue;

            // Empty string matches everything, and null is matched by everything
            var matches =
                query.Length == 0
                || (b.Text?.Contains(query, StringComparison.InvariantCultureIgnoreCase) ?? true);
            b.Visible = matches;
        }
    }

    private void Choose(int optionIndex)
    {
        OnOptionChosen?.Invoke(optionIndex);
        Close();
    }
}
