using System.Numerics;
using Content.Client._Floof.Paint;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Paint;
using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Floof.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LoadoutMetadataEditorDialog : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entSys = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    public event Action<Loadout>? OnSave;

    private readonly ProtoId<LoadoutPrototype> _loadoutProto;
    private readonly ProtoId<LoadoutGroupPrototype> _groupProto;
    private Loadout _loadout;

    private LoadoutContainer _previewContainer;

    public LoadoutMetadataEditorDialog(Loadout currentState, ProtoId<LoadoutPrototype> loadoutProto, ProtoId<LoadoutGroupPrototype> groupProto)
    {
        IoCManager.InjectDependencies(this);
        _entSys.TryGetEntitySystem<LoadoutSystem>(out var loadoutSystem); // I don't want to bother passing it through the constructor
        _protoMan.TryIndex(loadoutProto, out var loadoutProtoResolved);

        _loadoutProto = loadoutProto;
        _groupProto = groupProto;
        RobustXamlLoader.Load(this);

        // We maintain a copy of the original loadout to avoid polluting the character profile in the event the user decides not to save the loadout
        _loadout = new Loadout(currentState);

        // Preview container shows current loadout
        _previewContainer = new(loadoutProto, true, FormattedMessage.FromMarkupPermissive("Preview"));
        _previewContainer.Name = _loadout.NameOverride ?? (loadoutProtoResolved != null ? loadoutSystem?.GetName(loadoutProtoResolved) : "<error>");
        LoadoutPreviewContainer.AddChild(_previewContainer);

        Load(_loadout);

        CancelButton.OnPressed += _ => Close();
        SaveButton.OnPressed += _ =>
        {
            Save();
            Close();
        };

        CustomColorEnabled.OnToggled += args =>
        {
            ColorSelector.Visible = args.Pressed;
        };
    }

    public void Load(Loadout currentState)
    {
        CustomNameField.Text = currentState.NameOverride is { Length: >0 } nameOverride ? nameOverride : string.Empty;
        CustomDescField.Text = currentState.DescriptionOverride is { Length: >0 } descOverride ? descOverride : string.Empty;

        CustomColorEnabled.Pressed = currentState.ColorOverride != null;
        ColorSelector.Visible = CustomColorEnabled.Pressed;
        ColorSelector.Color = currentState.ColorOverride is { Length: > 0 } customColor
            ? Color.FromHex(customColor, Color.White)
            : Color.White;

        ColorEntity(_previewContainer.SpriteEntity, ColorSelector.Color, _entMan);
    }

    public void Save(bool raiseEvent = true)
    {
        // Sanitize data: empty text fields means no override, disabled color tint means no color tint
        string? customName = CustomNameField.Text.Trim();
        string? customDesc = CustomDescField.Text.Trim();
        Color? customColor = CustomColorEnabled.Pressed ? ColorSelector.Color : null;

        if (customName.Length == 0)
            customName = null;
        if (customDesc.Length == 0)
            customDesc = null;
        // Ideally this should be done server-side but w/e, this is just to prevent players from hurting each other's eyes by making completely black items
        if (customColor != null)
            customColor = SharedColorPaintSystem.ClampBrightness(customColor.Value, 0.25f, 1f);

        _loadout.NameOverride = customName;
        _loadout.DescriptionOverride = customDesc;
        _loadout.ColorOverride = customColor?.ToHexNoAlpha();

        if (raiseEvent)
            OnSave?.Invoke(_loadout);

        Load(_loadout); // Just to update the fields with sanitized values
    }

    // Helper method to color an entity
    public static void ColorEntity(EntityUid? ent, string? color, IEntityManager entMan)
    {
        Color? c = color == null ? null : Color.FromHex(color, Color.White);
        ColorEntity(ent, c, entMan);
    }

    public static void ColorEntity(EntityUid? ent, Color? color, IEntityManager entMan)
    {
        if (!entMan.EntityExists(ent) || entMan.Deleted(ent))
            return;

        // Dont waste time coloring every loadout
        if (color == null && !entMan.HasComponent<ColorPaintedComponent>(ent)
            || !entMan.TrySystem<ColorPaintSystem>(out var colorPaint))
            return;

        if (color != null)
            colorPaint.Paint(null, null, ent.Value, color.Value);
        else
            colorPaint.ClearPaint(ent.Value);
    }
}
